name: wallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #path_drawing: ^0.4.0
  sqflite:
  path:
  intl:
  charts_flutter:

  infinite_listview: ^1.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  assets:
    - images/classify_baby.png
    - images/classify_baby_gray.png
    - images/classify_cloth.png
    - images/classify_cloth_gray.png
    - images/classify_dailyuse.png
    - images/classify_dailyuse_gray.png
    - images/classify_define.png
    - images/classify_doctor.png
    - images/classify_doctor_gray.png
    - images/classify_eat.png
    - images/classify_eat_gray.png
    - images/classify_edu.png
    - images/classify_edu_gray.png
    - images/classify_face.png
    - images/classify_face_gray.png
    - images/classify_fangdai.png
    - images/classify_fruit.png
    - images/classify_fruit_gray.png
    - images/classify_game.png
    - images/classify_game_gray.png
    - images/classify_gift.png
    - images/classify_income_baoxiao.png
    - images/classify_income_baoxiao_gray.png
    - images/classify_income_bonus.png
    - images/classify_income_bonus_gray.png
    - images/classify_income_buzhu.png
    - images/classify_income_buzhu_gray.png
    - images/classify_income_finance.png
    - images/classify_income_finance_gray.png
    - images/classify_income_gift.png
    - images/classify_income_gift_gray.png
    - images/classify_income_jijin.png
    - images/classify_income_jijin_gray.png
    - images/classify_income_parttime.png
    - images/classify_income_parttime_gray.png
    - images/classify_income_redpacket.png
    - images/classify_income_redpacket_gray.png
    - images/classify_income_refund.png
    - images/classify_income_refund_gray.png
    - images/classify_income_stock.png
    - images/classify_income_stock_gray.png
    - images/classify_income_wage.png
    - images/classify_income_wage_gray.png
    - images/classify_movie.png
    - images/classify_pet.png
    - images/classify_pet_gray.png
    - images/classify_shop.png
    - images/classify_shop_gray.png
    - images/classify_smoke.png
    - images/classify_smoke_gray.png
    - images/classify_snack.png
    - images/classify_snack_gray.png
    - images/classify_sport.png
    - images/classify_sport_gray.png
    - images/classify_traffic.png
    - images/classify_traffic_gray.png
    - images/classify_waterpower.png
    - images/classify_waterpower_gray.png
    - images/classify_transfer.png
    - images/icon_cash.png
    - images/icon_rbank_bj.png
    - images/icon_rbank_gd.png
    - images/icon_rbank_gf.png
    - images/icon_rbank_gs.png
    - images/icon_rbank_gz.png
    - images/icon_rbank_hx.png
    - images/icon_rbank_js.png
    - images/icon_rbank_jt.png
    - images/icon_rbank_ms.png
    - images/icon_rbank_ny.png
    - images/icon_rbank_pa.png
    - images/icon_rbank_pf.png
    - images/icon_rbank_sh.png
    - images/icon_rbank_xy.png
    - images/icon_rbank_yz.png
    - images/icon_rbank_zg.png
    - images/icon_rbank_zs.png
    - images/icon_rbank_zx.png
    - images/icon_weixin.png
    - images/icon_zhifubao.png

